core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from account.views import menu_pengguna, menu_pengguna_frontend
from pengaduan.views import dashboard, frontend, register, profil_sekolah

urlpatterns = [
    path("", frontend, name="frontend"),
    path("api/", include("pengaduan.urls")),
    path("register", register, name="register"),
    path("sekolah", profil_sekolah, name="sekolah"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("dashboard/", dashboard, name="dashboard"),
    path("admin/", admin.site.urls),
    path("menu/", menu_pengguna, name="menu_pengguna"),
    path("menu/frontend", menu_pengguna_frontend, name="menu_pengguna_frontend"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class AccountManager(BaseUserManager):
    def create_user(self, username, nama_lengkap, password=None):
        """
        Creates and saves a User with the given username, nama_lengkap and password.
        """
        if not username:
            raise ValueError("Users must have an username")
        user = self.model(
            username=username,
            nama_lengkap=nama_lengkap,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, nama_lengkap, password):
        """
        Creates and saves a superuser with the given identity number,
        nama_lengkap and password.
        """
        user = self.create_user(username, password=password, nama_lengkap=nama_lengkap)
        user.is_admin = True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


# Create your models here.
class Account(AbstractUser):
    nama_lengkap = models.CharField("Nama Lengkap", max_length=150)
    alamat = models.CharField("Alamat", max_length=255, null=True, blank=True)
    desa = models.ForeignKey(
        "master.Desa", on_delete=models.SET_NULL, null=True, blank=True
    )
    tempat_lahir = models.CharField(
        max_length=255, verbose_name="Tempat Lahir", null=True, blank=True
    )
    tanggal_lahir = models.DateField(null=True, blank=True)

    objects = AccountManager()
    nomor_hp = models.BigIntegerField(default=0)
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["nama_lengkap"]

    def __str__(self):
        return self.nama_lengkap

    class Meta:
        ordering = ["id"]
        verbose_name = "Akun"
        verbose_name_plural = "Akun"


class Petugas(Account):
    kecamatan_penugasan = models.ForeignKey(
        "master.Kecamatan",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name="Petugas Kecamatan",
    )

    def __str__(self):
        return "Petugas Kecamatan {} - {} - {}".format(
            self.kecamatan_penugasan.nama if self.kecamatan_penugasan else "-",
            self.username,
            self.nama_lengkap,
        )

    class Meta:
        ordering = ["id"]
        verbose_name = "Petugas"
        verbose_name_plural = "Petugas"


@receiver(post_save, sender=Petugas)
def create_petugas_group(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name="Petugas"))
        instance.is_staff = True
        instance.is_active = True
        instance.save()


class AdminSekolah(Account):
    sekolah = models.ForeignKey("master.Sekolah", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return "Admin Sekolah {} - {}".format(self.username, self.nama_lengkap)

    class Meta:
        ordering = ["id"]
        verbose_name = "Admin Sekolah"
        verbose_name_plural = "Admin Sekolah"


@receiver(post_save, sender=AdminSekolah)
def create_adminsekolah_group(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name="Admin Sekolah"))
        instance.is_staff = True
        instance.is_active = True
        instance.save()


class Masyarakat(Account):
    nik = models.CharField(max_length=255, null=True, blank=True, verbose_name="NIK Pelapor")
    rt = models.IntegerField(null=True, default=0, verbose_name="RT")
    rw = models.IntegerField(null=True, default=0, verbose_name="RW")
    dusun = models.CharField(max_length=255, null=True, blank=True, verbose_name="Dusun")

    def __str__(self):
        return self.nama_lengkap

    class Meta:
        ordering = ["id"]
        verbose_name = "Masyarakat"
        verbose_name_plural = "Masyarakat"


@receiver(post_save, sender=Masyarakat)
def create_masyarakat_group(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name="Masyarakat"))
        instance.is_staff = True
        instance.is_active = True
        instance.save()

account/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from account.models import Account, Masyarakat, Petugas, AdminSekolah
from django.contrib.auth.models import Group
from master.models import Kecamatan, Desa


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    group = forms.ModelMultipleChoiceField(
        label="Menu",
        queryset=Group.objects.all(),
        required=False,
        widget=FilteredSelectMultiple(verbose_name="Menu", is_stacked=False),
    )

    class Meta:
        model = Account
        fields = ("email",)


class ProfileForm(forms.ModelForm):
    kecamatan = forms.ModelChoiceField(
        required=False,
        queryset=Kecamatan.objects.none(),
        widget=forms.Select(attrs={"onChange": "getDesa($(this))"}),
    )
    desa = forms.ModelChoiceField(queryset=Desa.objects.none(), required=False)

    def __init__(self, *args, **kwargs):
        if not hasattr(self, "request"):
            self.request = kwargs.pop("request", None)
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields["kecamatan"].to_field_name = "kode"
        self.fields["desa"].to_field_name = "kode"
        if "kecamatan" in self.data:
            try:
                kec_pk = int(self.data.get("kecamatan"))
                self.fields["kecamatan"].queryset = Kecamatan.objects.filter(
                    kode=kec_pk
                )
            except (ValueError, TypeError):
                pass

        if "desa" in self.data:
            try:
                des_pk = int(self.data.get("desa"))
                self.fields["desa"].queryset = Desa.objects.filter(kode=des_pk)
            except (ValueError, TypeError):
                pass

    class Meta:
        model = Account
        fields = (
            "nama_lengkap",
            "email",
            "tempat_lahir",
            "tanggal_lahir",
            "kecamatan",
            "desa",
            "alamat",
        )


class ProfileMasyarakatForm(forms.ModelForm):
    kecamatan = forms.ModelChoiceField(
        required=False,
        queryset=Kecamatan.objects.none(),
        widget=forms.Select(attrs={"onChange": "getDesa($(this))"}),
    )
    desa = forms.ModelChoiceField(queryset=Desa.objects.none(), required=False)
    nik = forms.CharField(max_length=16, widget=forms.NumberInput(), label="NIK Pelapor")

    alamat = forms.CharField(widget=forms.Textarea(), required=False)

    def __init__(self, *args, **kwargs):
        if not hasattr(self, "request"):
            self.request = kwargs.pop("request", None)
        super(ProfileMasyarakatForm, self).__init__(*args, **kwargs)
        self.fields["kecamatan"].to_field_name = "kode"
        self.fields["desa"].to_field_name = "kode"
        if "kecamatan" in self.data:
            try:
                kec_pk = int(self.data.get("kecamatan"))
                self.fields["kecamatan"].queryset = Kecamatan.objects.filter(
                    kode=kec_pk
                )
            except (ValueError, TypeError):
                pass

        if "desa" in self.data:
            try:
                des_pk = int(self.data.get("desa"))
                self.fields["desa"].queryset = Desa.objects.filter(kode=des_pk)
            except (ValueError, TypeError):
                pass

    class Meta:
        model = Masyarakat
        fields = (
            "nik",
            "username",
            "nama_lengkap",
            "tempat_lahir",
            "tanggal_lahir",
            "nomor_hp",
            "kecamatan",
            "desa",
            "dusun",
            "rt",
            "rw",
            "alamat",
        )


class ProfileAdminSekolahForm(forms.ModelForm):
    kecamatan = forms.ModelChoiceField(
        required=False,
        queryset=Kecamatan.objects.none(),
        widget=forms.Select(attrs={"onChange": "getDesa($(this))"}),
    )
    desa = forms.ModelChoiceField(queryset=Desa.objects.none(), required=False)

    alamat = forms.CharField(widget=forms.Textarea() ,required=False)

    def __init__(self, *args, **kwargs):
        if not hasattr(self, "request"):
            self.request = kwargs.pop("request", None)
        super(ProfileAdminSekolahForm, self).__init__(*args, **kwargs)
        self.fields["kecamatan"].to_field_name = "kode"
        self.fields["desa"].to_field_name = "kode"
        if "kecamatan" in self.data:
            try:
                kec_pk = int(self.data.get("kecamatan"))
                self.fields["kecamatan"].queryset = Kecamatan.objects.filter(
                    kode=kec_pk
                )
            except (ValueError, TypeError):
                pass

        if "desa" in self.data:
            try:
                des_pk = int(self.data.get("desa"))
                self.fields["desa"].queryset = Desa.objects.filter(kode=des_pk)
            except (ValueError, TypeError):
                pass

    class Meta:
        model = AdminSekolah
        fields = (
            "username",
            "nama_lengkap",
            "sekolah",
            "tempat_lahir",
            "tanggal_lahir",
            "kecamatan",
            "desa",
            "alamat",
            "nomor_hp",
        )


class ProfilePetugasForm(forms.ModelForm):
    kecamatan = forms.ModelChoiceField(
        required=False,
        queryset=Kecamatan.objects.none(),
        widget=forms.Select(attrs={"onChange": "getDesa($(this))"}),
    )
    desa = forms.ModelChoiceField(queryset=Desa.objects.none(), required=False)

    alamat = forms.CharField(widget=forms.Textarea(), required=False)

    def __init__(self, *args, **kwargs):
        if not hasattr(self, "request"):
            self.request = kwargs.pop("request", None)
        super(ProfilePetugasForm, self).__init__(*args, **kwargs)
        self.fields["kecamatan"].to_field_name = "kode"
        self.fields["desa"].to_field_name = "kode"
        if "kecamatan" in self.data:
            try:
                kec_pk = int(self.data.get("kecamatan"))
                self.fields["kecamatan"].queryset = Kecamatan.objects.filter(
                    kode=kec_pk
                )
            except (ValueError, TypeError):
                pass

        if "desa" in self.data:
            try:
                des_pk = int(self.data.get("desa"))
                self.fields["desa"].queryset = Desa.objects.filter(kode=des_pk)
            except (ValueError, TypeError):
                pass

    class Meta:
        model = Petugas
        fields = (
            "username",
            "nama_lengkap",
            "tempat_lahir",
            "tanggal_lahir",
            "kecamatan",
            "desa",
            "alamat",
            "nomor_hp",
        )

templates/frontend/profil_sekolah.html
{% extends 'frontend/base_site_frontend.html' %}
{% load widgets static %}

{% block custom_style %}
{{ block.super }}
<style>
    .fb-profile{
        border-top-right-radius: 20px;
        border-top-left-radius: 20px;
        border-bottom-right-radius: 20px;
        border-bottom-left-radius: 20px;
        margin-bottom: 10px;
    }
    .fb-profile img.fb-image-lg{
        z-index: 0;
        width: 100%;  
        height: 250px;
        object-fit: cover;
        margin-bottom: 10px;
        border-top-right-radius: 20px;
        border-top-left-radius: 20px;
    }
    
    .fb-image-profile
    {
        margin: -90px 10px 0px 50px;
        z-index: 9;
        width: 150px; 
        height: 150px;
        border-radius: 50%;
        object-fit: cover; 
        background-color: white;
    }
    hr{
        margin-top: 0.3rem;
        margin-bottom: 0.3rem;
    }
    @media (max-width:768px)
    {
        
    .fb-profile-text>h1{
        font-weight: 700;
        font-size:16px;
    }
    
    .fb-image-profile
    {
        margin: -45px 10px 0px 25px;
        z-index: 9;
        width: 20%; 
    }
    }
    .nav.nav-pills .nav-link.active, .nav.nav-pills .show > .nav-link{
        background-color: #3a567c;
    }
</style>
{% endblock custom_style %}

{% block content %}
<div class="card" id="card-profil">
    <div class="card-header">
        <h2 class="card-title m-0 p-1" style="text-align: center;">
            Profil Sekolah
        </h2>
    </div>
    <div class="card-body py-0">
        <div class="d-flex justify-content-center mt-5 mb-5">
            <div class="col-md-4">
                <select class="form-control" name="sekolah" id="id_sekolah"></select>
            </div>
        </div>
        <div class="profile-page mt-5" id="profile_page">
            <div class="fb-profile">
                <img align="left" class="fb-image-lg" id="header_sekolah" src="{% static 'img' %}/bg-5.jpg" alt="Profile image example"/>
                <img align="left" class="fb-image-profile thumbnail" id="profil" src="{% static 'img' %}/bg-5.jpg" alt="Profile image example"/>
                <div class="fb-profile-text">
                    <h1 id="nama_sekolah">Nama Sekolah</h1>
                    <p id="kode_sekolah">Kode sekolah</p>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="card">
                            <div class="card-body p-3">
                                <div class="form-group m-0">
                                    <label for="exampleFormControlInput1">Kepala Sekolah: </label>
                                    <br>
                                    <span id="kepala_sekolah">-</span>
                                </div>
                                <hr>
                                <div class="form-group m-0">
                                    <label for="exampleFormControlInput1">Operator Sekolah: </label>
                                    <br>
                                    <span id="operator_sekolah">-</span>
                                </div>
                                <hr>
                                <div class="d-flex justify-content-center">
                                    <a href="http://" id="no_hp" target="_blank" rel="noopener noreferrer"> <i class="fab fa-whatsapp fa-2x" style="color: #00ff11;"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="card">
                            <div class="card-header p-3">
                                <ul class="nav nav-pills" id="pills-tab" role="tablist">
                                    <li class="nav-item">
                                      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Profil</a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Data Siswa</a>
                                    </li>
                                  </ul>
                            </div>
                            <div class="card-body">
                                  <div class="tab-content" id="pills-tabContent">
                                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                                        <div class="table-responsive">
                                            <table class="table table-hover">
                                                {% for item in field %}
                                                <tr>
                                                    <td>{{item|replace:"_| "|title}}</td>
                                                    <td>:</td>
                                                    <td><span id="{{item}}">-</span></td>
                                                </tr>
                                                {% endfor %}
                                            </table>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
                                        <div class="table-responsive">
                                            <table class="table table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>No</th>
                                                        <th>Nama</th>
                                                        <th>Alamat</th>
                                                        <!-- <th>Tempat, Tanggal lahir</th> -->
                                                    </tr>
                                                </thead>
                                                <tbody id="data_anak" >
                                                    <tr>
                                                        <td colspan="3" style="text-align: center;">Tidak ada Data</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="pt-2 d-flex justify-content-between">
                                            <button type="button" class="btn btn-sm btn-secondary font-weight-bolder" id="sebelumnya"><i class="fas fa-arrow-left"></i> Sebelumnya</button>
                                            <button type="button" class="btn btn-sm btn-secondary font-weight-bolder" id="selanjutnya">Selanjutnya <i class="fas fa-arrow-right"></i></button>
                                          </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block custom_js %}
{{ block.super }}
<script>
    const get_data_sekolah = (sekolah=null, url=null) =>{
            var default_url = "/api/pengaduan/list-pengaduan"
            $("#selanjutnya").prop('disabled',true)
            $("#sebelumnya").prop('disabled',true)
            var data = {
                sekolah:sekolah
              }
            if(url){
              default_url = url
              data = null
            }
              $.ajax({
                url:default_url,
                method:'GET',
                data:data,
                beforeSend:function(){
                  Swal.fire({
                    title: 'Alert',
                    text: 'Proses Ambil Data, Harap tunggu',
                    showConfirmButton: false,
                    allowEscapeKey : false,
                    allowOutsideClick: false,
                    didOpen: () => {
                      Swal.showLoading()
                    },
                  })
                },
                success:function(respon){
                  Swal.close()
                  count = 2
                  var index = 0
                  get_page = new window.URLSearchParams(default_url)
                  if(get_page.get('page')){
                    index = (parseInt(get_page.get('page')) - 1) * count
                  }
                  if(respon.count > 0){
                    if(respon.next){
                      $("#selanjutnya").prop('disabled',false)
                      $("#selanjutnya").attr('onClick',`get_data_sekolah(null,'${respon.next}')`)
                    }
                    if(respon.previous){
                      $("#sebelumnya").prop('disabled',false)
                      $("#sebelumnya").attr('onClick',`get_data_sekolah(null,'${respon.previous}')`)
                    }
                    var html;
                    respon.results.map((value, idx) => {
                      html += `
                        <tr>
                          <td>${idx+1+index}</td>
                          <td><nobr>${value.nama}</nobr></td>
                          <td>${value.alamat}</td>
                          </tr>
                          `
                    })
                    $("#data_anak").html(html)
                  }else{
                    html = `
                    <tr>
                      <td colspan='4' style='text-align:center'>Tidak ada data Siswa di Sekolah ini</td>  
                      </tr>
                      `
                    $("#data_anak").html(html)
                  }
                }
              })
            
    }
    const formatResult = (result) => {
        if (result.loading) return result.text;
        if(result.profil){
            profil = `<img src="${result.profil}" class="symbol-label" style="object-fit: cover;" alt="">`
        }else{
            profil = `<span class="symbol-label font-size-h1 font-weight-bold text-uppercase">${result.text.charAt(0).toUpperCase()}</span>`
        }
        let html = `<options value="${result.id}">
                        <div class="d-flex align-items-center">

                            <div class="symbol symbol-light-success symbol-60 symbol-xxl-100 mr-5 align-self-start align-self-xxl-center">
                                ${profil}
                            </div>
                            <div>
                                <a href="#" class="font-weight-bold font-size-h5 text-dark-75 text-hover-primary">${result.kode_sekolah}</a>
                                <div class="text-muted data-nama_lengkap">${result.text}</div>
                            </div>
                        </div>
                    </options>`;
        //return html;
        return $(html);
    };
    $("#id_sekolah").select2({
        width: 'resolve',
        placeholder: `Cari Sekolah`,
        delay: 250,
        ajax: {
            url: '{% url 'admin:master_sekolah_json' %}',
            data: function (params) {
              var query = {
                q: params.term,
              }
        
              // Query parameters will be ?search=[term]&type=public
              return query;
            },
            processResults: function(data){
                console.log(data)
                return {
                    results: data.data
                }
            },
        },
        minimumInputLength: 3,
        templateResult: formatResult,
        minimumResultsForSearch: 20,
    })
    $('#id_sekolah').on('select2:select', function (e) {
        var data = e.params.data;
        let card_profil = new KTCard('card-profil');
        $.ajax({
            url:"{% url 'admin:master_sekolah_json_frontend' %}",
            data:{
                pk:data.id
            },
            beforeSend:function(){
                KTApp.block(card_profil.getSelf(), {
                    overlayColor: '#ffffff',
                    type: 'loader',
                    state: 'primary',
                    opacity: 0.3,
                    size: 'lg'
                });
            },
            success:function(res){
                if(Object.keys(res).length){
                    $("#profile_page").show()
                    $("#profil").attr('src',res.foto_sekolah)
                    $("#no_hp").attr('href',res.nomor_hp)
                    $("#header_sekolah").attr('src',res.background_header)
                    $("#nama_sekolah").html(res.nama_sekolah)
                    $("#kode_sekolah").html(res.kode_sekolah)
                    $("#kepala_sekolah").html(res.kepala_sekolah)
                    $("#operator_sekolah").html(res.operator_sekolah)
                    Object.keys(res.profile).map((item)=>{
                        $("#"+item).html(res.profile[item])
                    });
                    get_data_sekolah(data.id, null)
                }else{
                    $("#profile_page").hide()
                }
            },
            complete: function(){
                setTimeout(KTApp.unblock(card_profil.getSelf()), 1000);
            }
        })
    });
    $(function(){
        $("#profile_page").hide()
    })
</script>

{% endblock custom_js %}

templates/frontend/register.html
{% extends 'frontend/base_site_frontend.html' %}
{% load widgets %}

{% block custom_style %}
{{ block.super }}
<style>
    .field-hidden {
        display: none;
    }
    .legend{
		background-color: rgb(70, 69, 69);
	    font-size: 13pt;
	    padding-left: 10px;
	    font-weight: bold;
	    margin-top: 10px;
	    margin-bottom: 10px;
		color: white;
	}
</style>
{% endblock custom_style %}
{% block messages %}
{% if messages %}
{% for message in messages %}
<div
    class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'warning' %}warning{% elif message.tags == 'success' %}success{% else %}info{% endif %} alert-dismissible {% if beranda %}mt-15{% endif %}">
    {% if message.tags == 'error' %}
    <h5><i class="icon fas fa-ban"></i> Error!</h5>
    {% elif message.tags == 'warning' %}
    <h5><i class="icon fas fa-exclamation-triangle"></i> Peringatan!</h5>
    {% elif message.tags == 'success' %}
    <h5><i class="icon fas fa-check"></i> Success!</h5>
    {% else %}
    <h5><i class="icon fas fa-info"></i> Info!</h5>
    {% endif %}
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endblock messages %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h2 class="card-title m-0 p-1" style="text-align: center;">
            Register
        </h2>
    </div>
    <form action="" method="post">
        <div class="card-body">
            {% csrf_token %}
            <div class="row">
                {% for field in forms %}
                <div class="col-md-6{% if field.is_hidden %} field-hidden{% endif %}">
                    <div class="mb-3">
                        {% if field|is_bool %}
                        {{field}}
                        <label for="{{field.auto_id}}" class="form-label {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
                        {% elif field|is_select %}
                        <label for="{{field.id}}" class="form-label {% if field.field.required %}required{% endif %}">{{field.label }}</label>
                        {{ field|addcls:"form-control" }}
                        {% elif field|is_hidden %}
                        {{ field }}
                        {% else %}
                        <label for="{{field.id}}" class="form-label {% if field.field.required %}required{% endif %}">{{field.label }}</label>
                        {{ field|addcls:'form-control' }}
                        {% endif %}
                        {% if field.field.help_text %}
                        <div id="{{field.id}}" style="font-weight: bolder;" class="form-text">{{field.field.help_text}}
                        </div>
                        {% endif %}
                        {% if field.errors %}
                        <p style=" color: red; background-color: #fadbd8;">{{field.errors|striptags}}</p>
                        {% endif %}
                    </div>
                </div>
                {% if field.name == "nomor_hp" %}
                </div>
                <h2 class="legend">
                    Alamat
                </h2>
                <div class="row">
                {% endif %}
                {% if field.name == "alamat" %}
                </div>
                <hr>
                <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
</div>
<div class="card-footer">
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-success"><i class="fas fa-user-plus"></i> Register</button>
    </div>
</div>
</form>
</div>
{% endblock content %}

{% block custom_js %}
{{ block.super }}
<script>
    const getKecamatan = () => {
        $.ajax({
            url: `{% url 'admin:master_kecamatan_json' %}`,
            type: "GET",
            success: function (respon) {
                html = `<option readonly value="">Pilih Kecamatan</option>`
                for (i = 0; i < respon.data.length; i++) {
                    html += `<option value="${respon.data[i].id}">${respon.data[i].text}</option>`
                }
                $("#id_kecamatan").html(html).prop("disabled", false).select2({
                    width: 'resolve'
                })
            }
        })
    }
    const getDesa = (elemen) => {
        kecamatan_kode = elemen.val()
        $.ajax({
            url: `{% url 'admin:master_desa_json' %}?kode_kecamatan=${kecamatan_kode}`,
            type: "GET",
            success: function (respon) {
                if (respon.success) {
                    html = `<option readonly value="">Pilih Desa</option>`
                    for (i = 0; i < respon.data.length; i++) {
                        html += `<option value="${respon.data[i].id}">${respon.data[i].text}</option>`
                    }
                    $("#id_desa").html(html).prop("disabled", false).select2({
                        width: 'resolve'
                    })
                } else {
                    console.log(respon.pesan)
                }
            }
        })
    }
    $(function () {
        getKecamatan()
    })
</script>
{% endblock custom_js %}